CREATE DATABASE Venda

CREATE TABLE Lucas(
Id INT NOT NULL PRIMARY KEY,
Idade INT NOT NULL UNIQUE,
Cidade Varchar(MAX) NULL
)

ALTER TABLE DBO.Lucas
	ADD UF Char(2) NULL, TelefoneNumber INT NOT NULL;

DROP TABLE Lucas

CREATE TABLE VEICULO(
Id INT PRIMARY KEY ,
Descricao VARCHAR(100) NOT NULL,
DataCriacao DATETIME NOT NULL,
TipoMotor DECIMAL NOT NULL,
Valor MONEY NULL,
Vendido BIT NOT NULL
)

CREATE TABLE COR(
Id INT PRIMARY KEY,
NomeCor VARCHAR(100) NOT NULL UNIQUE
)